import type { VerifiedScenePlacement } from "./types";

export const VERIFIED_SCENE_PLACEMENT_ENTRIES = [
  {
    id: "placement.bench_center_stand.v1",
    version: "1.0.0",
    displayName: "Center dispensing station",
    equipmentDefinitionId: "component.burette.v1",
    visualAdapterDefinitionId: "visual-adapter.burette.v1",
    anchorId: "anchor.dispense.center.v1",
    assemblyId: "assembly.dispense_station.v1",
    translation: [0, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [0.16, 0.16],
    footprintHalfExtentsXZ: [0.12, 0.08],
    rotationOrder: 0
  },
  {
    id: "placement.bench_center_stand_reversed.v1",
    version: "1.0.0",
    displayName: "Center dispensing station, controls reversed",
    equipmentDefinitionId: "component.burette.v1",
    visualAdapterDefinitionId: "visual-adapter.burette.v1",
    anchorId: "anchor.dispense.center.v1",
    assemblyId: "assembly.dispense_station.v1",
    translation: [0, 0, 0],
    yawRadians: Math.PI,
    footprintCenterXZ: [0.16, 0.16],
    footprintHalfExtentsXZ: [0.12, 0.08],
    rotationOrder: 1
  },
  {
    id: "placement.bench_left_stand.v1",
    version: "1.0.0",
    displayName: "Left dispensing station",
    equipmentDefinitionId: "component.burette.v1",
    visualAdapterDefinitionId: "visual-adapter.burette.v1",
    anchorId: "anchor.dispense.left.v1",
    assemblyId: "assembly.dispense_station.v1",
    translation: [-0.34, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [-0.18, 0.16],
    footprintHalfExtentsXZ: [0.12, 0.08],
    rotationOrder: 0
  },
  {
    id: "placement.bench_left_stand_reversed.v1",
    version: "1.0.0",
    displayName: "Left dispensing station, controls reversed",
    equipmentDefinitionId: "component.burette.v1",
    visualAdapterDefinitionId: "visual-adapter.burette.v1",
    anchorId: "anchor.dispense.left.v1",
    assemblyId: "assembly.dispense_station.v1",
    translation: [-0.34, 0, 0],
    yawRadians: Math.PI,
    footprintCenterXZ: [-0.18, 0.16],
    footprintHalfExtentsXZ: [0.12, 0.08],
    rotationOrder: 1
  },
  {
    id: "placement.under_burette.v1",
    version: "1.0.0",
    displayName: "Flask beneath center burette",
    equipmentDefinitionId: "component.erlenmeyer_flask.v1",
    visualAdapterDefinitionId: "visual-adapter.erlenmeyer_flask.v1",
    anchorId: "anchor.dispense.center.v1",
    assemblyId: "assembly.dispense_station.v1",
    translation: [0, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [0.18, 0.32],
    footprintHalfExtentsXZ: [0.1, 0.1],
    rotationOrder: 0
  },
  {
    id: "placement.under_left_burette.v1",
    version: "1.0.0",
    displayName: "Flask beneath left burette",
    equipmentDefinitionId: "component.erlenmeyer_flask.v1",
    visualAdapterDefinitionId: "visual-adapter.erlenmeyer_flask.v1",
    anchorId: "anchor.dispense.left.v1",
    assemblyId: "assembly.dispense_station.v1",
    translation: [-0.34, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [-0.16, 0.32],
    footprintHalfExtentsXZ: [0.1, 0.1],
    rotationOrder: 0
  },
  {
    id: "placement.indicator_shelf.v1",
    version: "1.0.0",
    displayName: "Indicator shelf on the left",
    equipmentDefinitionId: "component.indicator_bottle.v1",
    visualAdapterDefinitionId: "visual-adapter.indicator_bottle.v1",
    anchorId: "anchor.indicator.left.v1",
    assemblyId: null,
    translation: [0, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [-0.55, 0.05],
    footprintHalfExtentsXZ: [0.29, 0.09],
    rotationOrder: 0
  },
  {
    id: "placement.indicator_shelf_right.v1",
    version: "1.0.0",
    displayName: "Indicator shelf on the right",
    equipmentDefinitionId: "component.indicator_bottle.v1",
    visualAdapterDefinitionId: "visual-adapter.indicator_bottle.v1",
    anchorId: "anchor.indicator.right.v1",
    assemblyId: null,
    translation: [1.17, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [0.62, 0.05],
    footprintHalfExtentsXZ: [0.29, 0.09],
    rotationOrder: 0
  },
  {
    id: "placement.reagent_station.v1",
    version: "1.0.0",
    displayName: "Preparation supplies on the right",
    equipmentDefinitionId: "component.reagent_bottle.v1",
    visualAdapterDefinitionId: "visual-adapter.reagent_bottle.v1",
    anchorId: "anchor.reagent.right.v1",
    assemblyId: null,
    translation: [0, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [0.72, 0.12],
    footprintHalfExtentsXZ: [0.21, 0.14],
    rotationOrder: 0
  },
  {
    id: "placement.reagent_station_left.v1",
    version: "1.0.0",
    displayName: "Preparation supplies on the left",
    equipmentDefinitionId: "component.reagent_bottle.v1",
    visualAdapterDefinitionId: "visual-adapter.reagent_bottle.v1",
    anchorId: "anchor.reagent.left.v1",
    assemblyId: null,
    translation: [-1.34, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [-0.62, 0.12],
    footprintHalfExtentsXZ: [0.21, 0.14],
    rotationOrder: 0
  },
  {
    id: "placement.solution_pipette_stand.v1",
    version: "1.0.0",
    displayName: "Pipette stand",
    equipmentDefinitionId: "component.volumetric_pipette.v1",
    visualAdapterDefinitionId: "visual-adapter.volumetric_pipette.v1",
    anchorId: "anchor.solution.pipette.v1",
    assemblyId: null,
    translation: [0, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [-0.55, 0.18],
    footprintHalfExtentsXZ: [0.08, 0.08],
    rotationOrder: 0
  },
  {
    id: "placement.solution_flask_center.v1",
    version: "1.0.0",
    displayName: "Center volumetric-flask station",
    equipmentDefinitionId: "component.volumetric_flask.v1",
    visualAdapterDefinitionId: "visual-adapter.volumetric_flask.v1",
    anchorId: "anchor.solution.flask.v1",
    assemblyId: null,
    translation: [0, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [0, 0.2],
    footprintHalfExtentsXZ: [0.1, 0.1],
    rotationOrder: 0
  },
  {
    id: "placement.solution_stock_right.v1",
    version: "1.0.0",
    displayName: "Stock-solution station",
    equipmentDefinitionId: "component.reagent_bottle.v1",
    visualAdapterDefinitionId: "visual-adapter.reagent_bottle.v1",
    anchorId: "anchor.solution.stock.v1",
    assemblyId: null,
    translation: [-0.17, 0, 0.12],
    yawRadians: 0,
    footprintCenterXZ: [0.55, 0.15],
    footprintHalfExtentsXZ: [0.1, 0.1],
    rotationOrder: 0
  },
  {
    id: "placement.solution_wash_left.v1",
    version: "1.0.0",
    displayName: "Distilled-water station",
    equipmentDefinitionId: "component.wash_bottle.v1",
    visualAdapterDefinitionId: "visual-adapter.wash_bottle.v1",
    anchorId: "anchor.solution.wash.v1",
    assemblyId: null,
    translation: [0, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [-0.3, -0.08],
    footprintHalfExtentsXZ: [0.11, 0.11],
    rotationOrder: 0
  },
  {
    id: "placement.calorimeter_center.v1",
    version: "1.0.0",
    displayName: "Center coffee-cup calorimeter",
    equipmentDefinitionId: "component.calorimeter.v1",
    visualAdapterDefinitionId: "visual-adapter.calorimeter.v1",
    anchorId: "anchor.calorimetry.center.v1",
    assemblyId: null,
    translation: [0, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [0, 0.18],
    footprintHalfExtentsXZ: [0.12, 0.12],
    rotationOrder: 0
  },
  {
    id: "placement.calorimetry_thermometer.v1",
    version: "1.0.0",
    displayName: "Calorimetry thermometer station",
    equipmentDefinitionId: "component.thermometer.v1",
    visualAdapterDefinitionId: "visual-adapter.thermometer.v1",
    anchorId: "anchor.calorimetry.thermometer.v1",
    assemblyId: null,
    translation: [0, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [0.22, 0.1],
    footprintHalfExtentsXZ: [0.04, 0.04],
    rotationOrder: 0
  },
  {
    id: "placement.calorimetry_wash_left.v1",
    version: "1.0.0",
    displayName: "Calorimetry distilled-water station",
    equipmentDefinitionId: "component.wash_bottle.v1",
    visualAdapterDefinitionId: "visual-adapter.wash_bottle.v1",
    anchorId: "anchor.calorimetry.wash.v1",
    assemblyId: null,
    translation: [0, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [-0.35, -0.05],
    footprintHalfExtentsXZ: [0.11, 0.11],
    rotationOrder: 0
  },
  {
    id: "placement.calorimetry_stock_right.v1",
    version: "1.0.0",
    displayName: "Calorimetry aqueous-stock station",
    equipmentDefinitionId: "component.reagent_bottle.v1",
    visualAdapterDefinitionId: "visual-adapter.reagent_bottle.v1",
    anchorId: "anchor.calorimetry.stock.v1",
    assemblyId: null,
    translation: [0, 0, 0],
    yawRadians: 0,
    footprintCenterXZ: [0.45, 0.12],
    footprintHalfExtentsXZ: [0.1, 0.1],
    rotationOrder: 0
  }
] as const satisfies readonly VerifiedScenePlacement[];
